/* This file was generated by json2code.py */

#ifndef TESTRUN_H
#define TESTRUN_H

#ifndef __cplusplus
#endif /* __cplusplus */

#ifdef OVERRIDE
#define TESTRUN_H_CONST
#else
#define TESTRUN_H_CONST const
#endif /* OVERRIDE */

#ifdef INITIALIZE

TESTRUN_H_CONST int int_var = 1;
TESTRUN_H_CONST double decimal = 1.234;
TESTRUN_H_CONST double another_one = 0.034;
TESTRUN_H_CONST char string_var[500] = "hello world";
TESTRUN_H_CONST int b1 = 1;
TESTRUN_H_CONST int b2 = 0;
TESTRUN_H_CONST int int_arr[50] = {1, 2, 3};
TESTRUN_H_CONST double dbl_arr[50] = {1.2, 1e-10, 2.2};
TESTRUN_H_CONST double promoted_arr[50] = {1, 2, 1.3};
TESTRUN_H_CONST int bool_arr[50] = {1, 0};
TESTRUN_H_CONST char string_arr[50][500] = {"hello", "world", "again", "computer"};
TESTRUN_H_CONST double nested[50][50] = {{1, 2, 3}, {3, 2}, {1, 2.3}};

#else

extern TESTRUN_H_CONST int int_var;
extern TESTRUN_H_CONST double decimal;
extern TESTRUN_H_CONST double another_one;
extern TESTRUN_H_CONST char string_var[500];
extern TESTRUN_H_CONST int b1;
extern TESTRUN_H_CONST int b2;
extern TESTRUN_H_CONST int int_arr[50];
extern TESTRUN_H_CONST double dbl_arr[50];
extern TESTRUN_H_CONST double promoted_arr[50];
extern TESTRUN_H_CONST int bool_arr[50];
extern TESTRUN_H_CONST char string_arr[50][500];
extern TESTRUN_H_CONST double nested[50][50];

#endif /* INITIALIZE */

#endif /* TESTRUN_H */